//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ef6.Recipe1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EF6RecipesEntities1 : DbContext
    {
        public EF6RecipesEntities1()
            : base("name=EF6RecipesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Meter> Meters { get; set; }
        public DbSet<Poem> Poems { get; set; }
        public DbSet<Poet> Poets { get; set; }
        public DbSet<vwLibrary> vwLibraries { get; set; }
    }
}
